name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  flake8_check:
    runs-on: ubuntu-latest
    env:
      report_path: flake_report
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html
      - name: Create folder for artifact
        run: |
          mkdir ${{ env.report_path }}
      - name: Analysing the code with flake8
        run: flake8 --format=html --htmldir=${{ env.report_path }}
      - name: Save report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake report
          path: ${{ env.report_path }}

  mypy_check_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          python3 -m pip install types-redis
      - name: Check src
        run: |
          mypy ./simple_web_scraping